### ISSUE TITLE
How can I use it in IDEA

### ISSUE THREAD

**Issue by xgrommx** [yanex/dsl-preview#1]
I see that this plugin should work with your project koan. How can I use it?

**Comment by xgrommx** [comment]
@yanex Are you here?)

**Comment by yanex** [comment]
Yep.
Yes, This project was mainly created as a preview for Koan DSL, but it's still in beta.
You can build the project from sources and test the plugin, but README and binary builds are still have to be made.

**Comment by xgrommx** [comment]
@yanex I cannot find README file.

**Comment by xgrommx** [comment]
@yanex Can you help me?

**Comment by yanex** [comment]
Yes, I will publish the plugin zip and instructions today.

**Comment by yanex** [comment]
The pre-release is already here: https://github.com/yanex/dsl-preview/releases .
